CREATE TABLE USUARIOS
(
    USU_IDEN     INT IDENTITY (1,1) PRIMARY KEY,
    USU_LOGIN    VARCHAR(100) UNIQUE NOT NULL,
    USU_EMAIL    VARCHAR(300) NOT NULL,
    USU_NOME     VARCHAR(100) NOT NULL,
    USU_SENHA    VARCHAR(300)        NOT NULL,
    USU_CPF_CNPJ    VARCHAR(11)        NOT NULL,
    USU_TIPO    INTEGER ,
    USU_DTA_HORA DATETIME default getdate() ,
    USU_USU_IDEN INT,
    CONSTRAINT USU_USU_IDEN FOREIGN KEY (USU_USU_IDEN)
        REFERENCES USUARIOS (USU_IDEN)

);

CREATE TABLE tb_dependencia
(
    SEQ_DEPENDENCIA     INT IDENTITY (1,1) PRIMARY KEY,
    DESCR_DEPENDENCIA    VARCHAR(100),
    MSG_LINHA_OLD    VARCHAR(300),
    MSG_LINHA     VARCHAR(100),
    DE_ABREVIACAO    VARCHAR(300),
    IC_TIPO_DEPENDENCIA    VARCHAR(300),
    IC_ATIVO    VARCHAR ,
    PERIODO VARCHAR ,
    MES VARCHAR ,
    DIA VARCHAR ,

);

CREATE TABLE TB_RESERVA_DEPENDENCIAS
(
    SEQ_RESERVA INT IDENTITY (1,1),
    SEQ_DEPENDENCIA INT NOT NULL ,
    CD_CATEGORIA INT,
    CD_MATRICULA     INT,
    SEQ_DEPENDENTE    INT ,
    DT_INIC_UTILIZACAO  DATETIME,
    DT_HR_UTILIZACAO   DATETIME,
    NOME_INTERESSADO   VARCHAR(300) ,
    DT_RESERVA   DATETIME,
    DT_CONFIRMACAO   DATETIME,
    TEL_CONTATO   VARCHAR ,
    CD_STATUS_RESERVA VARCHAR,
    DE_CANC_RESERVA VARCHAR,
    DE_USER_CANC INT,
    DT_LIMITE_CONF DATETIME,
    NO_CONTATO VARCHAR,
    TEL_CONTATO_RES VARCHAR,
    QT_PUBLICO_PREVISTO INTEGER ,
    CD_TIPO_EVENTO INT ,
    HH_INIC_UTIL VARCHAR,
    HH_FIM_UTIL VARCHAR,
    IC_ORIGEM_RESERVA VARCHAR,
    DE_BLOQUEIO VARCHAR,
    USER_CONFIRMACAO VARCHAR ,
    PRIMARY KEY (SEQ_RESERVA, SEQ_DEPENDENCIA),

    FOREIGN KEY (SEQ_DEPENDENCIA)
        REFERENCES tb_dependencia (seq_dependencia),

    FOREIGN KEY (DE_USER_CANC )
        REFERENCES USUARIOS (USU_IDEN)

    --FOREIGN KEY (USER_CONFIRMACAO)
       --REFERENCES USUARIOS (USU_NOME)

);

CREATE TABLE GRUPOS
(
    GRP_IDEN      INT IDENTITY (1,1)  PRIMARY KEY ,
    GRP_NOME      VARCHAR(255) UNIQUE NOT NULL,
    GRP_DESCRICAO VARCHAR(255),
    GRP_DTA_HORA DATETIME default getdate() ,
    GRP_USU_IDEN  INT NOT NULL,
    FOREIGN KEY (GRP_USU_IDEN)
        REFERENCES USUARIOS (USU_IDEN)
);

CREATE TABLE USUARIOS_GRUPOS
(
    UGR_IDEN INT IDENTITY (1,1)  NOT NULL ,
    UGR_USU_IDEN INT NOT NULL,
    UGR_GRP_IDEN INT NOT NULL,
    UGR_DTA_HORA DATETIME default getdate(),
    PRIMARY KEY (UGR_IDEN, UGR_USU_IDEN, UGR_GRP_IDEN),
    FOREIGN KEY (UGR_USU_IDEN)
        REFERENCES GRUPOS (GRP_IDEN),
    FOREIGN KEY (UGR_USU_IDEN)
        REFERENCES USUARIOS (USU_IDEN)
);

CREATE TABLE PERMISSOES
(
    PER_IDEN      INT IDENTITY (1,1)  PRIMARY KEY,
    PER_DESCRICAO VARCHAR(100),
    PER_NOME      VARCHAR(50) NOT NULL,
    PER_DTA_HORA  DATETIME default getdate() ,
    PER_USU_IDEN  INT         NOT NULL,
    FOREIGN KEY (PER_USU_IDEN)
        REFERENCES USUARIOS (USU_IDEN)
);

CREATE TABLE GRUPOS_PERMISSOES
(
    GP_IDEN INT IDENTITY (1,1)  NOT NULL,
    GPE_GRP_IDEN INT NOT NULL,
    GPE_PER_IDEN INT NOT NULL,
    PRIMARY KEY (GP_IDEN,GPE_GRP_IDEN, GPE_PER_IDEN),
    FOREIGN KEY (GPE_GRP_IDEN)
        REFERENCES GRUPOS (GRP_IDEN),
    FOREIGN KEY (GPE_PER_IDEN)
        REFERENCES PERMISSOES (PER_IDEN)
);

CREATE TABLE MENUS
(
    MEN_IDEN       INT IDENTITY (1,1)  PRIMARY KEY,
    MEN_DESCRICAO  VARCHAR(255),
    MEN_ICONE      VARCHAR(255),
    MEN_ORDEM_MENU INT,
    MEN_URL        VARCHAR(255),
    MEN_NIVEL      INT       NOT NULL,
    MEN_MEN_IDEN   INT,
    MEN_DTA_HORA DATETIME default getdate() ,
    MEN_USU_IDEN   INT,
    FOREIGN KEY (MEN_MEN_IDEN)
        REFERENCES MENUS (MEN_IDEN),
    FOREIGN KEY (MEN_USU_IDEN)
        REFERENCES USUARIOS (USU_IDEN)

);

CREATE TABLE MENU_PERMISSOES
(
    MPE_INDE INT IDENTITY (1,1)  NOT NULL,
    MPE_MEN_IDEN INT NOT NULL,
    MPE_PER_IDEN INT NOT NULL,
    PRIMARY KEY (MPE_INDE,MPE_MEN_IDEN, MPE_PER_IDEN),
    FOREIGN KEY (MPE_MEN_IDEN)
        REFERENCES MENUS (MEN_IDEN),
    FOREIGN KEY (MPE_PER_IDEN)
        REFERENCES PERMISSOES (PER_IDEN)
);


INSERT INTO USUARIOS (USU_LOGIN, USU_EMAIL, USU_NOME, USU_SENHA, USU_CPF_CNPJ)
VALUES ('admin', 'admin@admin.com.br', 'Adminstrador do Sistema', '$2a$10$eqELFW4V3UBeBdjbnvnYjOED9Mmyr5WegakP7yfVlhJDalz3aEq1u', '70846792192');

UPDATE USUARIOS
SET USU_USU_IDEN = 1
WHERE USU_LOGIN = 'admin';



ALTER TABLE USUARIOS ALTER COLUMN USU_USU_IDEN int NOT NULL;

insert into GRUPOS (GRP_NOME, GRP_DESCRICAO, GRP_USU_IDEN)
values ('ADMIN', 'GRUPO DE ADMINSTRADORES', (SELECT USU_IDEN FROM USUARIOS WHERE USU_LOGIN = 'admin'));



insert into GRUPOS (GRP_NOME, GRP_DESCRICAO, GRP_USU_IDEN)
values ('SECRETARIA', 'GRUPO DE SECRETARIA', 1);


insert into usuarios_grupos (UGR_USU_IDEN, UGR_GRP_IDEN, UGR_DTA_HORA) values (1, 1, getdate() );

