CREATE TABLE PESSOAS
(
    PES_IDEN     INTEGER IDENTITY (1,1) PRIMARY KEY,
    PES_NOME_REG VARCHAR(255) NOT NULL,
    PES_NOME_SOC VARCHAR(255),
    PES_STATUS   INTEGER,
    PES_DTA_HORA DATETIME default GETDATE() NOT NULL,
    PES_USU_IDEN INTEGER          NOT NULL,
    CONSTRAINT PES_USU_IDEN_FK FOREIGN KEY (PES_USU_IDEN)
        REFERENCES USUARIOS (USU_IDEN)
);

CREATE TABLE CONTATOS_PESSOAS
(
    COP_IDEN       INTEGER IDENTITY (1,1) PRIMARY KEY,
    COP_PES_IDEN   INTEGER NOT NULL,
    COP_TIPO       VARCHAR(20),
    COP_PRINCIPAL  INTEGER,
    COP_CONTATO    VARCHAR(255),
    COP_OBSERVACAO VARCHAR(255),
    COP_DTA_INI    DATE,
    COP_DTA_FIM    DATE,
    COP_STATUS     INTEGER,
    COP_DTA_HORA   DATETIME default GETDATE() NOT NULL,
    COP_USU_IDEN   INTEGER,
    CONSTRAINT COP_PES_IDEN_FK FOREIGN KEY (COP_PES_IDEN)
        REFERENCES PESSOAS (PES_IDEN),
    CONSTRAINT COP_USU_IDEN_FK FOREIGN KEY (COP_USU_IDEN)
        REFERENCES USUARIOS (USU_IDEN)
);

CREATE TABLE ENDERECOS_PESSOAS
(
    END_IDEN            INTEGER IDENTITY (1,1) PRIMARY KEY,
    END_PES_IDEN        INTEGER NOT NULL,
    END_TIPO            VARCHAR(50),
    END_LOGRADOURO      VARCHAR(100),
    END_NUMERO          VARCHAR(50),
    END_COMPLEMENTO     VARCHAR(50),
    END_BAIRRO          VARCHAR(100),
    END_CEP             VARCHAR(10),
    END_CIDADE          VARCHAR(100),
    END_ESTADO          VARCHAR(50),
    END_UF              VARCHAR(2),
    END_STATUS          INTEGER,
    END_DTA_HORA        DATETIME default GETDATE() NOT NULL,
    END_USU_IDEN        INTEGER,
    CONSTRAINT END_PES_IDEN_FK FOREIGN KEY (END_PES_IDEN)
        REFERENCES PESSOAS (PES_IDEN),
    CONSTRAINT END_USU_IDEN_FK FOREIGN KEY (END_USU_IDEN)
        REFERENCES USUARIOS (USU_IDEN)
);

CREATE TABLE TIPO_AGRUPAMENTO
(
    TAGP_IDEN     INTEGER IDENTITY (1,1) PRIMARY KEY,
    TAGP_NOME     VARCHAR(50),
    TAGP_STATUS   INTEGER,
    TAGP_DTA_HORA DATETIME default GETDATE() NOT NULL,
    TAGP_USU_IDEN INTEGER,
    CONSTRAINT TAGP_USU_IDEN_FK FOREIGN KEY (TAGP_USU_IDEN)
        REFERENCES USUARIOS (USU_IDEN)
);

CREATE TABLE AGRUPAMENTOS_PESSOAS
(
    AGP_IDEN            INTEGER IDENTITY (1,1) PRIMARY KEY,
    AGP_PES_IDEN_ORIGEM INTEGER       NOT NULL,
    AGP_PES_IDEN_AGRP   INTEGER       NOT NULL,
    AGP_TAGP_IDEN       INTEGER       NOT NULL,
    AGP_DTA_HORA        DATETIME default GETDATE() NOT NULL,
    AGP_USU_IDEN        INTEGER       NOT NULL,
    CONSTRAINT AGP_PES_IDEN_ORIGEM_FK FOREIGN KEY (AGP_PES_IDEN_ORIGEM)
        REFERENCES PESSOAS (PES_IDEN),
    CONSTRAINT AGP_PES_IDEN_AGRP_FK FOREIGN KEY (AGP_PES_IDEN_AGRP)
        REFERENCES PESSOAS (PES_IDEN),
    CONSTRAINT AGP_TAGP_IDEN_FK FOREIGN KEY (AGP_TAGP_IDEN)
        REFERENCES TIPO_AGRUPAMENTO (TAGP_IDEN),
    CONSTRAINT AGP_USU_IDEN_FK FOREIGN KEY (AGP_USU_IDEN)
        REFERENCES USUARIOS (USU_IDEN)
);

CREATE TABLE PESSOAS_FISICAS
(
    PFI_IDEN           INTEGER IDENTITY (1,1) PRIMARY KEY,
    PFI_PES_IDEN       INTEGER,
    PFI_SEXO           CHAR(1),
    PFI_DTA_NASCIMENTO DATE,
    PFI_NATURALIDADE   VARCHAR(100),
    PFI_NACIONALIDADE  VARCHAR(100),
    PFI_EST_CIVIL      VARCHAR(10),
    PFI_CPF            VARCHAR(14),
    PFI_RG             VARCHAR(30),
    PFI_RG_ORG_EMISSOR VARCHAR(50),
    PFI_DTA_EMISSAO    DATE,
    PFI_NOME_MAE       VARCHAR(200),
    PFI_NOME_PAI       VARCHAR(200),
    PFI_STATUS         INTEGER,
    PFI_DTA_HORA       DATETIME default GETDATE() NOT NULL,
    PFI_USU_IDEN       INTEGER       NOT NULL,
    CONSTRAINT PFI_PES_IDEN_FK FOREIGN KEY (PFI_PES_IDEN)
        REFERENCES PESSOAS (PES_IDEN),
    CONSTRAINT PFI_USU_IDEN_FK FOREIGN KEY (PFI_USU_IDEN)
        REFERENCES USUARIOS (USU_IDEN)
);

CREATE TABLE PESSOAS_JURIDICAS
(
    PJU_IDEN           INTEGER IDENTITY (1,1) PRIMARY KEY,
    PJU_PES_IDEN       INTEGER         NOT NULL,
    PJU_CNPJ           VARCHAR(30) NOT NULL,
    PJU_INS_MUNI       VARCHAR(50),
    PJU_INS_EST        VARCHAR(50),
    PJU_IND_FORNECEDOR INTEGER,
    PJU_STATUS         INTEGER,
    PJU_DTA_HORA       DATETIME default GETDATE() NOT NULL,
    PJU_USU_IDEN       INTEGER         NOT NULL,
    CONSTRAINT PJU_PES_IDEN_FK FOREIGN KEY (PJU_PES_IDEN)
        REFERENCES PESSOAS (PES_IDEN),
    CONSTRAINT PJU_USU_IDEN_FK FOREIGN KEY (PJU_USU_IDEN)
        REFERENCES USUARIOS (USU_IDEN)
);





